site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
theme: readthedocs

pages:
- Home: 'index.md'
- Quick start:
  - 'Getting started': 'getting_started.md'
  # - 'Running the simulator': 'running_simulator_standalone.md'
  # - 'Connecting a Python client': 'connecting_the_client.md'
  - 'Configuring the simulation': 'configuring_the_simulation.md'
  # - 'Measurements': 'measurements.md'
  - 'Cameras and sensors': 'cameras_and_sensors.md'
  - 'F.A.Q.': 'faq.md'
- Driving Benchmark:
  - 'Quick Start': 'benchmark_start.md'
  - 'General Structure': 'benchmark_structure.md'
  - 'Creating Your Benchmark': 'benchmark_creating.md'
  - 'Computed Performance Metrics': 'benchmark_metrics.md'
- Building from source:
  - 'How to build on Linux': 'how_to_build_on_linux.md'
  - 'How to build on Windows': 'how_to_build_on_windows.md'
- Advanced topics:
  - 'CARLA Settings': 'carla_settings.md'
  - 'Python API': 'python_api.md'
  # - 'Simulator keyboard input': 'simulator_keyboard_input.md'
  - 'Running without display and selecting GPUs': 'carla_headless.md'
  - 'Running in a Docker': 'carla_docker.md'
  - "How to link Epic's Automotive Materials": 'epic_automotive_materials.md'
- Contributing:
  - 'Contribution guidelines': 'CONTRIBUTING.md'
  - 'Coding standard': 'coding_standard.md'
  - 'Code of conduct': 'CODE_OF_CONDUCT.md'
- Development:
  - 'Map customization': 'map_customization.md'
  # - 'CARLA design': 'carla_design.md'
  # - 'CarlaServer documentation': 'carla_server.md'
  - 'Build system': 'build_system.md'
- Art guidelines:
  - 'How to add assets': 'how_to_add_assets.md'
  - 'How to model vehicles': 'how_to_model_vehicles.md'
- Appendix:
  - 'Driving Benchmark Sample Results Town01': 'benchmark_basic_results_town01.md'
  - 'Driving Benchmark Sample Results Town02': 'benchmark_basic_results_town02.md'



markdown_extensions:
  - admonition
