# carla original variable name is used unchanged here (i.e CamelCase, etc)
carla:
  host: localhost
  port: 2000
  QualityLevel: Low  # Low or Epic
  SynchronousMode: True

  sensors:
    CameraRGB:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: SceneFinal
        ImageSizeX: 800
        ImageSizeY: 600
        FOV: 90
        PositionX: -5.00
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 0

    camera_depth:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: Depth
        ImageSizeX: 800
        ImageSizeY: 600
        FOV: 90
        PositionX: -5.00
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 0

    camera_depth_front:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: Depth
        ImageSizeX: 800
        ImageSizeY: 600
        FOV: 90
        PositionX: 7.00
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 180

    CameraRGB_front:
      SensorType: CAMERA
      carla_settings:
        PostProcessing: SceneFinal
        ImageSizeX: 800
        ImageSizeY: 600
        FOV: 90
        PositionX: 7.00
        PositionY: 0
        PositionZ: 1.30
        RotationPitch: 0
        RotationRoll: 0
        RotationYaw: 180




    #camera_semantic_segmentation:
    #  SensorType: CAMERA
    #  carla_settings:
    #    PostProcessing: SemanticSegmentation
    #    ImageSizeX: 800
    #    ImageSizeY: 600
    #    FOV: 90
    #    PositionX: 0.00
    #    PositionY: 0
    #    PositionZ: 1.30
    #    RotationPitch: 0
    #    RotationRoll: 0
    #    RotationYaw: 0


    lidar_0:
      SensorType: LIDAR_RAY_CAST
      carla_settings:
        Channels: 4
        Range: 120
        PointsPerSecond: 200000
        RotationFrequency: 25
        UpperFovLimit: 1.6
        LowerFovLimit: -1.6 
        PositionX: 0.0
        PositionY: 0
        PositionZ: 1.50
        RotationPitch: 0
        RotationYaw: 0
        RotationRoll: 0
